config/routes.rb
Istanbulcare::Application.routes.draw do

  get "static_pages/home"

  devise_for :doctors
  
  devise_scope :doctor do
    get "doctors/search_patient" => "doctors#search_patient", as: :search_patient
    match "doctors/:id" => "doctors#show", as: :doctor
  end
  
  devise_for :patients
  
  devise_scope :patient do
    match "patients/:id" => "patients#show", as: :patient
  end
  
  resources :prescriptions
  resources :visuals
  resources :vaccines
  resources :operations
  match 'visuals/:id' => "visuals#show", as: :visual
  match "vaccines/:id" => "vaccines#show", as: :vaccine
  match "operations/:id" => "operations#show", as: :operation
  
  root to: "static_pages#home"

end

app/views/shared/_details.html.erb
<div id = "main-content">
	<div id = "section-box-one"class="well">
		<h3 class = "section-title">Reçeteler</h3>
		<%= render partial: "prescriptions/prescription", collection: prescriptions, as: :prescription %>
  		<div class = "add-patient-record">
  			<%= link_to "Reçete Ekle", new_prescription_path(patient_tc_no: "#{@patient.tc_no}"), class: "btn btn-primary btn-small" if doctor_signed_in? %>
  		</div>
	</div><!--well-->

	<div id = "section-box-one" class="well">
		<h3 class = "section-title">Gorseller</h3>
		<%= render partial: "visuals/visual", collection: visuals, as: :visual %>
  		<div class = "add-patient-record">
  			<%= link_to "Görsel Ekle", new_visual_path(patient_tc_no: "#{@patient.tc_no}"), class: "btn btn-primary btn-small" if doctor_signed_in? %>
  		</div>
	</div><!--well-->

	<div id = "section-box-one" class="well">
		<h3 class = "section-title">Aşılar</h3>
		<%= render partial: "vaccines/vaccine", collection: vaccines, as: :vaccine %>
  		<div class = "add-patient-record">
  			<%= link_to "Aşı Ekle", new_vaccine_path(patient_tc_no: "#{@patient.tc_no}"), class: "btn btn-primary btn-small" if doctor_signed_in? %>
  		</div>
	</div><!--well-->
  
	<div id = "section-box-one" class="well">
		<h3 class = "section-title">Operasyonlar</h3>
		<%= render partial: "operations/operation", collection: operations, as: :operation %>
  		<div class = "add-patient-record">
  			<%= link_to "Operasyon Ekle", new_operation_path(patient_tc_no: "#{@patient.tc_no}"), class: "btn btn-primary btn-small" if doctor_signed_in? %>
  		</div>
	</div><!--well-->
</div>