config/routes.rb
Istanbulcare::Application.routes.draw do

  get "static_pages/home"

  devise_for :doctors
  
  devise_scope :doctor do
    get "doctors/search_patient" => "doctors#search_patient", as: :search_patient
    match "doctors/:id" => "doctors#show", as: :doctor
  end
  
  devise_for :patients
  
  devise_scope :patient do
    match "patients/:id" => "patients#show", as: :patient
  end
  
  resources :prescriptions
  resources :visuals
  resources :vaccines
  resources :operations
  match 'visuals/:id' => "visuals#show", as: :visual
  match "vaccines/:id" => "vaccines#show", as: :vaccine
  match "operations/:id" => "operations#show", as: :operation
  
  root to: "static_pages#home"

end

app/views/layouts/_footer.html.erb
     <div class = "navbar navbar-default navbar-fixed-bottom footer-bar">
            <div id = "footer-text" class = "navbar-text pull-left">İstanbul Sağlık Hizmetleri powered by Bizimkafa</div>
            <div class = "footer-button">
            	<a id = "contact-button" href = "" class = "navbar-btn btn-danger btn pull-right">Bize Ulaşın</a>
            </div>
    </div><!--navbar-bottom

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
<%= link_to "Istanbul Sağlık Hizmetleri", static_pages_home_path, class: "brand" %>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active">
                        <%= link_to "Ana Sayfa", static_pages_home_path, class: "", contenteditable: "false" %>
                    </li>      
                    <%if doctor_signed_in? || patient_signed_in? %>
                        <li>
                            <a href="#" class="" contenteditable="false">Kişisel Bilgilerim</a>
                        </li>
                             <li><a href="#" class="" contenteditable="false">Example</a>
                        </li>
                        <% if doctor_signed_in? %>
                          <li id = "exit-nav-item">
                              <%= link_to "Çıkış", destroy_doctor_session_path, method: :delete %>
                          </li>
                        <% elsif patient_signed_in? %>
                          <li id = "exit-nav-item">
                              <%= link_to "Çıkış", destroy_patient_session_path, method: :delete %>
                          </li>
                        <% end %>
                        <li id = "username-nav-item">
                          <% if doctor_signed_in? %>
                            <h4 id = "user-name"><%= link_to current_doctor.full_name, current_doctor  %></h4>
                          <% elsif patient_signed_in? %>
                            <h4 id = "user-name"><%= link_to current_patient.full_name, current_patient  %></h4>
                          <% end %>
                        </li>
                        
                    <%end%>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="span2">
  <!--sidebar-->
  <% unless !(doctor_signed_in? ^ patient_signed_in?) && !current_page?(:controller => 'doctors', :action => 'show') %>
    <div id = "proper-sidebar" class="sidebar-nav-fixed" data-spy="affix" data-offset-top="140">
        <ul class="nav">
            <hr style="margin: 0px; border-width: 3px">
            <li>
                <%= link_to "Reçeteler", doctor_signed_in? ? search_patient_path(tc_no: "#{@patient.id}") : current_patient, class: "sidebar-item", contenteditable: "false" %>
            </li>
            <hr style="margin: 0px; border-width: 3px">
            <li>
                <a href="#" class="sidebar-item" contenteditable="false">Görseller</a>
            </li>
            <hr style="margin: 0px; border-width: 3px">
            <li>
                <a href="#" class="sidebar-item">Tahlil Sonuçları</a>
            </li>
            <hr style="margin: 0px; border-width: 3px">
            <li>
                <a href="#" class="sidebar-item">Aşılar</a>
            </li>
            <hr style="margin: 0px; border-width: 3px">
            <li>
                <a href="#" class="sidebar-item">Alerjiler</a>
            </li>
            <hr style="margin: 0px; border-width: 3px">

        </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>İstanbul Sağlık Hizmetleri</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header"%>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
   <div class="container">
      <div class="row">
          <div class="span7">
            <%= yield %>
          </div>
      </div><!--rowFluid-->
   </div>   
    <%= render partial: "layouts/footer"%>
    <!--<%= debug(params) if Rails.env.development? %>-->
  </body>
</html>