config/routes.rb
Istanbulcare::Application.routes.draw do

  get "static_pages/home"

  devise_for :doctors
  
  devise_scope :doctor do
    get "doctors/search_patient" => "doctors#search_patient", as: :search_patient
    match "doctors/:id" => "doctors#show", as: :doctor
  end
  
  devise_for :patients
  
  devise_scope :patient do
    match "patients/:id" => "patients#show", as: :patient
  end
  
  resources :prescriptions
  resources :visuals
  resources :vaccines
  resources :operations
  match 'visuals/:id' => "visuals#show", as: :visual
  match "vaccines/:id" => "vaccines#show", as: :vaccine
  match "operations/:id" => "operations#show", as: :operation
  
  root to: "static_pages#home"

end

app/models/operation.rb
# == Schema Information
#
# Table name: operations
#
#  id         :integer          not null, primary key
#  patient_id :integer
#  date       :date
#  notes      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tip_first  :string(255)
#  tip_second :string(255)
#

class Operation < ActiveRecord::Base
  belongs_to :patient
  attr_accessible :date, :notes, :tip_first, :tip_second
  
  def tip
    "#{tip_second} #{tip_second}"
  end

  def format_date
    self.date.strftime("%d/%m/%Y")
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

  def show
    @operation = Operation.find params[:id]
  end
  
  def new
    @patient = Patient.find_by_tc_no params[:patient_tc_no]
    @operation = @patient.operations.new
  end
  
  def create
    @patient = Patient.find params[:patient_id]
    @operation = @patient.operations.new params[:operation]
    
    respond_to do |format|
      if @operation.save
        format.html { redirect_to(@operation, :notice => 'Operasyon basariyla olusturuldu.') }
        format.xml  { render :xml => @operation, :status => :created, :location => @operation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= simple_form_for(@operation, html: { class: "form-horizontal" } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= hidden_field_tag :patient_id,  "#{@patient.id}" %>
    <%= f.input :tip_first, label: "Operasyon Bolgesi" %>
    <%= f.input :tip_second, label: "Operasyon Cesidi" %>
    <%= f.input :date, label: "Yapilis Tarihi" %>
    <%= f.input :notes, as: :text, input_html: { cols: 52, rows: 5 } %>
  </div>

  <div class="form-actions">
    <%= f.submit "Olustur", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<%= link_to operation.format_date, operation, class: "record-date" %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/new.html.erb
<h1>Yeni Operasyon</h1>

<%= render 'form' %>

<%= link_to 'Back', search_patient_path(tc_no: params[:patient_tc_no]), class: "btn btn-warning btn-small" %>

app/views/operations/show.html.erb
<div id = "general-section">
    <h1 class = "visual-header"><%= "#{@operation.format_date} Tarihli Operasyon" %></h1>
    <div id = "visual-type">
        <div class = "info-title">Türü: <%= @operation.tip %></div>
    </div>    
    <div id="visuals-section">            
        <div id ="visual-left-column">
            <p class = "info-title">Yapilis Tarihi: <%= @operation.format_date %></p>
        </div>
        <div id ="visual-right-column">
             <p class = "info-title" >Açıklamalar</p>
             <div> 
                 <p id="explanations"><%= @operation.notes %>!</p>
             </div>              
        </div>      
    </div>
</div>